# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Dropcorn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dropcorn

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end
