fastlane_version "2.95"

####################
# GENERAL CONFIG
####################

before_all do
   ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end


####################
# IOS 
####################

platform :ios do
    before_all do
        cocoapods(
          use_bundle_exec: false, 
          podfile: "ios"
          )
    end

    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :beta do
    match(
        type: "appstore", 
        git_url: "git@andrewSelden.github.com:andrewselden/certificates.git" 
     ) 
    increment_build_number(
        xcodeproj: "ios/Dropcorn.xcodeproj"
    )

    build_app(scheme: "Dropcorn",
            workspace: "ios/Dropcorn.xcworkspace",
            clean: true,
            scheme: "Dropcorn",
            silent: false, 
            include_bitcode: false
            )

    changelog_from_git_commits

    upload_to_testflight
  end

  lane :release do
     match(
        type: "appstore", 
        git_url: "git@andrewSelden.github.com:andrewselden/certificates.git" 
        )
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

#  error do |lane, exception|
#     slack(
#       message: exception.message,
#       success: false
#     )
#  end
end


####################
# ANDROID 
####################

platform :android do
  before_all do
  end

  desc "Build a local apk"
  lane :local_apk do

  end

  desc "This will distribute a build to the internal track of the play store"
  lane :beta_internal do
       gradle(
        project_dir: 'android',
        task: 'assemble',
        build_type: 'Release'
     )
     google_play_track_version_codes
     upload_to_play_store(track: 'internal')
     slack(message: 'Android: Successfully distributed a new beta build to internal track')

  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end

##################
# TEST 
##################
lane :test do
    slack(
      message: "Hey G. This is an automated message."
    )
end


