export const userActionTypes = {
    SIGNIN: {
     REQUESTED: 'SIGNIN.REQUESTED',
     FULFILLED: 'SIGNIN.FULFILLED',
     REJECTED: 'SIGNIN.REJECTED'
    },
     SIGNOUT: {
     REQUESTED: 'SIGNOUT.REQUESTED',
     FULFILLED: 'SIGNOUT.FULFILLED',
     REJECTED: 'SIGNOUT.REJECTED'
    },
    SIGNUP: {
     REQUESTED: 'SIGNUP.REQUESTED',
     FULFILLED: 'SIGNUP.FULFILLED',
     REJECTED: 'SIGNUP.REJECTED'
    },
    UPDATEEMAIL: {
     REQUESTED: 'UPDATEEMAIL.REQUESTED',
     FULFILLED: 'UPDATEEMAIL.FULFILLED',
     REJECTED: 'UPDATEEMAIL.REJECTED'
    },
    PASSWORDRESET: {
     REQUESTED: 'PASSWORDRESET.REQUESTED',
     FULFILLED: 'PASSWORDRESET.FULFILLED',
     REJECTED: 'PASSWORDRESET.REJECTED'
    },
    UPDATEPROFILE: {
      REQUESTED: 'UPDATEPROFILE.REQUESTED',
      FULFILLED: 'UPDATEPROFILE.FULFILLED',
      REJECTED: 'UPDATEPROFILE.REJECTED'
    },
   ROOT_CHANGE: {
       REQUESTED: 'ROOT_CHANGE.REQUESTED'
    },
    SYNC_USER: 'SYNC_USER'
}
