export const authentication = {
   LOGIN: {
    REQUESTED: 'LOGIN.REQUESTED',
    FULFILLED: 'LOGIN.FULFILLED',
    REJECTED: 'LOGIN.REJECTED'
  },
  SIGNUP: {
    REQUESTED: 'SIGNUP.REQUESTED',
    FULFILLED: 'SIGNUP.FULFILLED',
    REJECTED: 'SIGNUP.REJECTED'
  },
  PASSWORDRESET: {
    REQUESTED: 'PASSWORDRESET.REQUESTED',
    FULFILLED: 'PASSWORDRESET.FULFILLED',
    REJECTED: 'PASSWORDRESET.REJECTED'
  },
  LOGOUT: {
    REQUESTED: 'LOGOUT.REQUESTED',
    FULFILLED: 'LOGOUT.FULFILLED',
    REJECTED: 'LOGOUT.REJECTED'
  },
  ROOT_CHANGE: {
      REQUESTED: 'ROOT_CHANGE.REQUESTED'
  },
  SYNC_USER: 'SYNC_USER'
}

