export const userActionTypes = {
    SIGNIN: {
     REQUESTED: 'SIGNIN.REQUESTED',
     FULFILLED: 'SIGNIN.FULFILLED',
     REJECTED: 'SIGNIN.REJECTED'
    },
     SIGNOUT: {
     REQUESTED: 'SIGNOUT.REQUESTED',
     FULFILLED: 'SIGNOUT.FULFILLED',
     REJECTED: 'SIGNOUT.REJECTED'
    },
    SIGNUP: {
     REQUESTED: 'SIGNUP.REQUESTED',
     FULFILLED: 'SIGNUP.FULFILLED',
     REJECTED: 'SIGNUP.REJECTED'
    },
    UPDATEEMAIL: {
     REQUESTED: 'UPDATEEMAIL.REQUESTED',
     FULFILLED: 'UPDATEEMAIL.FULFILLED',
     REJECTED: 'UPDATEEMAIL.REJECTED'
    },
    PASSWORDRESET: {
     REQUESTED: 'PASSWORDRESET.REQUESTED',
     FULFILLED: 'PASSWORDRESET.FULFILLED',
     REJECTED: 'PASSWORDRESET.REJECTED'
    },
    UPDATEPROFILE: {
      REQUESTED: 'UPDATEPROFILE.REQUESTED',
      FULFILLED: 'UPDATEPROFILE.FULFILLED',
      REJECTED: 'UPDATEPROFILE.REJECTED'
    },
   ROOT_CHANGE: {
       REQUESTED: 'ROOT_CHANGE.REQUESTED'
    },
    SYNC_USER: 'SYNC_USER'
}

export const kernelActionTypes = {
    ADD_TEXT_ITEM: {
        REQUESTED: 'ADD_TEXT_ITEM.REQUESTED',
        REJECTED: 'ADD_TEXT_ITEM.REJECTED',
        FULFILLED: 'ADD_TEXT_ITEM.FULFILLED'
    },
    ADD_FILE_ITEM: {
        REQUESTED: 'ADD_FILE_ITEM.REQUESTED',
        REJECTED: 'ADD_FILE_ITEM.REJECTED',
        FULFILLED: 'ADD_FILE_ITEM.FULFILLED'
    },
    ADD_IMAGE_ITEM: {
        REQUESTED: 'ADD_IMAGE_ITEM.REQUESTED',
        REJECTED: 'ADD_IMAGE_ITEM.REJECTED',
        FULFILLED: 'ADD_IMAGE_ITEM.FULFILLED'
    },
    TIMER: {
        START: 'KERNEL_TIMER_START',
        STOP: 'KERNEL_TIMER_STOP',
        TICK: 'KERNEL_TIMER_TICK',
        RESET: 'KERNEL_TIMER_RESET'
    },
    UPDATE_KERNEL_ITEMS: 'UPDATE_KERNEL_ITEMS'
}

export const downloadActionTypes = {
    DOWNLOAD_FILE: {
        REQUESTED: 'DOWNLOAD_FILE.REQUESTED',
        FULFILLED: 'DOWNLOAD_FILE.FULFILLED',
        REJECTED: 'DOWNLOAD_FILE.REJECTED'
    }
}

export const clipboardActionTypes = {
    READ_FROM_CLIPBOARD: {
        REQUESTED: 'READ_FROM_CLIPBOARD.REQUESTED',
        FULFILLED: 'READ_FROM_CLIPBOARD.FULFILLED',
        REJECTED: 'READ_FROM_CLIPBOARD.REJECTED'
    },
    WRITE_TO_CLIPBOARD: {
        REQUESTED: 'WRITE_TO_CLIPBOARD.REQUESTED',
        FULFILLED: 'WRITE_TO_CLIPBOARD.FULFILLED',
        REJECTED: 'WRITE_TO_CLIPBOARD.REJECTED'
    }
}

export const locationBrowserActionTypes = {
    INITIALIZE: 'RADAR.INITIALIZE',
    BACKGROUND_TRACKING_ON: {
        REQUESTED: 'BACKGROUND_TRACKING_ON.REQUESTED',
        FULFILLED: 'BACKGROUND_TRACKING_ON.FULFILLED',
        REJECTED: 'BACKGROUND_TRACKING_ON.REJECTED'
    },
    BACKGROUND_TRACKING_OFF: {
        REQUESTED: 'BACKGROUND_TRACKING_OFF.REQUESTED',
        FULFILLED: 'BACKGROUND_TRACKING_OFF.FULFILLED',
        REJECTED: 'BACKGROUND_TRACKING_OFF.REJECTED'
    },
    UPDATE_PERMISSIONS: {
        REQUESTED: 'UPDATE_PERMISSIONS.REQUESTED',
        FULFILLED: 'UPDATE_PERMISSIONS.FULFILLED',
        REJECTED: 'UPDATE_PERMISSIONS.REJECTED'
    },
    UPDATE_LOCATION: {
        REQUESTED: 'UPDATE_LOCATION.REQUESTED',
        FULFILLED: 'UPDATE_LOCATION.FULFILLED',
        REJECTED: 'UPDATE_LOCATION.REJECTED'
    },
    UPDATE_LOCATION_KERNELS: {
        REQUESTED: 'UPDATE_LOCATION_KERNELS.REQUESTED',
        FULFILLED: 'UPDATE_LOCATION_KERNELS.FULFILLED',
        REJECTED: 'UPDATE_LOCATION_KERNELS.REJECTED'
    },
    SYNC_KERNELS: 'LOCATION_BROWSER.SYNC_KERNELS'
}

export const alertActionTypes = {
}
