export const auth = {
  LOGIN: {
    REQUESTED: 'LOGIN.REQUESTED',
    FULFILLED: 'LOGIN.FULFILLED',
    REJECTED: 'LOGIN.REJECTED'
  },
  LOGOUT: {
    REQUESTED: 'LOGOUT.REQUESTED',
    FUFILLED: 'LOGOUT.FULFILLED',
    REJECTED: 'LOGOUT.REJECTED'
  },
  SYNC_USER: 'SYNC_USER'
}

